### ISSUE TITLE
The folders which are "test_den", "test_img' and "test lab" are none.

### ISSUE THREAD

**Issue by ZachZou-logs** [RQuispeC/multi-stream-crowd-counting#1]
Hello, thank you for your code. When I use your code in ucf_cc_50, I find the folders which are "test_den", "test_img' and "test lab" are none in every fold. And the information of the error is that:
`Traceback (most recent call last):
  File "main.py", line 241, in <module>
    main()
  File "main.py", line 236, in main
    train(train_test, out_dir_root)
  File "main.py", line 149, in train
    mae, mse = evaluate_model(save_name, data_loader_val, save_test_results=args.save_plots, plot_save_dir=osp.join(output_dir, 'plot-results-train/'))
  File "E:\multi-stream-crowd-counting\architecture\evaluate_model.py", line 35, in evaluate_model
    mae = mae/(data_loader.get_num_samples())
ZeroDivisionError: float division by zero
`
Looking forward to your reply!

**Comment by RQuispeC** [comment]
Hey sorry, I didn't see this issue... In case you are still working with our code make sure to preprocess the data (steps must be available on readme) _den directory has the density maps and _lab has the labels to generate those density maps
