### ISSUE TITLE
Broken dataset link

### ISSUE THREAD

**Issue by kuraga** [RQuispeC/multi-stream-crowd-counting#2]
Hello, @RQuispeC !

Seems like dataset link (http://www.liv.ic.unicamp.br/~quispe/publications/data/data-crowd-counting.zip) is broken. Is it possible to fix it?

And: is there a pretrained model?

Thanks!

**Comment by RQuispeC** [comment]
Hi @kuraga, that data is available in the servers of my lab and I don't have a local copy of them. Sadly, those servers are down with no estimated time of being repaired.

In the meantime you can use the data from the original dataset authors
https://www.crcv.ucf.edu/data/ucf-cc-50/
https://github.com/desenzhou/ShanghaiTechDataset

**Comment by kuraga** [comment]
@RQuispeC , thanks!

That data == trained data?

**Comment by RQuispeC** [comment]
yes! just make sure to move the folders to match

```
ROOT_OF_REPO
    data
        ucf_cc_50
            UCF_CC_50
                images
                labels
        ShanghaiTech
            part_A
                train_data
                    images
                    ground-truth
                test_data
                    images
                    ground-truth
            part_B
                train_data
                    images
                    ground-truth
                test_data
                    images
                    ground-truth
```
